### ISSUE TITLE
vraptor4 running from wildfy 10

### ISSUE THREAD

**Issue by masumcse1** [caelum/vraptor4#1025]
17:40:02,157 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.deployment.unit."events.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."events.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type CacheStore<String, String> with qualifiers @LRU
  at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject public br.com.caelum.vraptor.view.DefaultAcceptHeaderToFormat(@LRU CacheStore<String, String>)
  at br.com.caelum.vraptor.view.DefaultAcceptHeaderToFormat.<init>(DefaultAcceptHeaderToFormat.java:60)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Managed Bean [class br.com.caelum.vraptor.cache.DefaultCacheStore] with qualifiers [@Default @Any]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

17:40:02,164 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "events.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"events.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"events.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type CacheStore<String, String> with qualifiers @LRU
  at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject public br.com.caelum.vraptor.view.DefaultAcceptHeaderToFormat(@LRU CacheStore<String, String>)
  at br.com.caelum.vraptor.view.DefaultAcceptHeaderToFormat.<init>(DefaultAcceptHeaderToFormat.java:60)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Managed Bean [class br.com.caelum.vraptor.cache.DefaultCacheStore] with qualifiers [@Default @Any]
"}}
17:40:02,248 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "events.war" (runtime-name : "events.war")
17:40:02,254 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."events.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."events.war".WeldStartService: Failed to start service

17:40:02,370 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
17:40:02,370 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
17:40:02,371 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.0.0.Beta2 (WildFly Core 2.0.0.Beta4) started (with errors) in 9210ms - Started 540 of 967 services (175 services failed or missing dependencies, 306 services are lazy, passive or on-demand)
17:40:02,421 INFO  [org.jboss.as.jpa] (ServerService Thread Pool -- 2) WFLYJPA0011: Stopping Persistence Unit (phase 2 of 2) Service 'events.war#default'
17:40:02,425 INFO  [org.jboss.as.jpa] (ServerService Thread Pool -- 2) WFLYJPA0011: Stopping Persistence Unit (phase 1 of 2) Service 'events.war#default'
17:40:02,425 INFO  [org.jboss.weld.deployer] (MSC service thread 1-2) WFLYWELD0010: Stopping weld service for deployment events.war
17:40:02,491 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment events.war (runtime-name: events.war) in 95ms
17:40:02,532 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0009: Undeployed "events.war" (runtime-name: "events.war")
17:40:02,540 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."events.war".WeldBootstrapService (missing) dependents: [service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.sql.UpdateTag".WeldInstantiator, service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag".WeldInstantiator, service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.core.OutTag".WeldInstantiator, service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag".WeldInstantiator, WFLYCTL0208: ... and 82 more ] 
      service jboss.deployment.unit."events.war".WeldStartService (missing) dependents: [service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.sql.UpdateTag".WeldInstantiator, service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag".WeldInstantiator, service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.core.OutTag".WeldInstantiator, service jboss.deployment.unit."events.war".component."org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag".WeldInstantiator, WFLYCTL0208: ... and 84 more ] 
      service jboss.deployment.unit."events.war".component.EventService.CREATE (missing) dependents: [service jboss.deployment.unit."events.war".component.EventService.START] 
      service jboss.deployment.unit."event

**Comment by Turini** [comment]
hi @masumcse1, which VRaptor version are you using? 
If I'm not wrong, this bug was fixed by https://github.com/caelum/vraptor4/pull/917. It should to work if you're using `vraptor 4.1.4` +

**Comment by masumcse1** [comment]
i am trying to deploy   application vraptor-musicjungle. i am using vraptor 
<version>4.2.0-RC3</version>

**Comment by Turini** [comment]
did it work for you using the latest version?

**Comment by masumcse1** [comment]
yes it is work for latest version in wildfy 10 for 4.2.0-RC3

**Comment by Turini** [comment]
Very nice! I'm closing here, ok? Please, reopen if you get any problem. Thanks
