### ISSUE TITLE
Exception with Weblogic: Cannot inherit from final class

### ISSUE THREAD

**Issue by gouvermxt** [caelum/vraptor4#1087]
When I try to deploy an app tha uses vraptor 4.2.0-RC5 in Weblogic 12.1.3, I receive the following error:

`weblogic.application.ModuleException: java.lang.VerifyError: Cannot inherit from final class
	at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
	at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:175)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:170)
	at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:412)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:366)
	Truncated. see log file for complete stacktrace`

If I remove the vraptor dependency declaration in the pom.xml, the app deploys succesfully.

**Comment by pwener** [comment]
I think this is not a problem with vraptor, probably something in your build, please send your full log. Try use a previous version of vraptor too.

**Comment by gouvermxt** [comment]
This is the full log:

`<26/01/2017 15h53min47s AMST> <Error> <Deployer> <BEA-149265> <Failure occurred in the execution of deployment request with ID "2449787105293" for task "2". Error is: "weblogic.application.ModuleException: java.lang.VerifyError: Cannot inherit from final class"
weblogic.application.ModuleException: java.lang.VerifyError: Cannot inherit from final class
	at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
	at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:175)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:170)
	at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:412)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:366)
	Truncated. see log file for complete stacktrace
> 
<26/01/2017 15h53min47s AMST> <Warning> <Deployer> <BEA-149004> <Failures were detected while initiating distribute task for application "teste_vraptor-1.0.0-dev-SNAPSHOT".> 
<26/01/2017 15h53min47s AMST> <Warning> <Deployer> <BEA-149078> <Stack trace for message 149004
weblogic.application.ModuleException: java.lang.VerifyError: Cannot inherit from final class
	at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
	at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:175)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:170)
	at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:412)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:366)
	Truncated. see log file for complete stacktrace
> 
<26/01/2017 15h53min48s AMST> <Error> <Console> <BEA-240003> <Administration Console encountered the following error: weblogic.application.ModuleException: java.lang.VerifyError: Cannot inherit from final class
	at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
	at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:175)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:170)
	at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
	at weblogic.work.ContextWrap.run(ContextWrap.java:40)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:553)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
Caused by: java.lang.VerifyError: Cannot inherit from final class

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:412)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:366)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:318)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:186)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass(ChangeAwareClassLoader.java:50)
	at com.oracle.injection.integration.BeanLoaderUtils.loadBeanClassesFromJar(BeanLoaderUtils.java:54)
	at com.oracle.injection.integration.BeanLoaderUtils.loadBeanClassesFromEmbeddedJar(BeanLoaderUtils.java:34)
	at com.oracle.injection.integration.CDIModuleExtension.loadBeanClassesFromEmbeddedJar(CDIModuleExtension.java:750)
	at com.oracle.injection.integration.CDIModuleExtension.makeInjectionArchivesForResourceType(CDIModuleExtension.java:549)
	at com.oracle.injection.integration.CDIModuleExtension.createLibInjectionArchives(CDIModuleExtension.java:507)
	at com.oracle.injection.integration.CDIModuleExtension.createWebModuleInjectionArchive(CDIModuleExtension.java:214)
	at com.oracle.injection.integration.CDIModuleExtension.createInjectionArchive(CDIModuleExtension.java:200)
	at com.oracle.injection.integration.CDIModuleExtension.postPrepare(CDIModuleExtension.java:95)
	at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:297)
	at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:285)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)
	at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:109)
> 
`

The same build deploys successfully on Wildfly 8.2.1 Final. I´ve tried to deploy several other VRaptor versions on Weblogic, but no one of the 4+ versions worked. 

I was able to deploy a project with the 3.5.5 version in Weblogic, but I want to use a 4+ version.
