### ISSUE TITLE
Forward/redirect(String) doesn't work

### ISSUE THREAD

**Issue by garcia-jj** [caelum/vraptor4#72]
java.lang.RuntimeException: java.lang.String is final
    at javassist.util.proxy.ProxyFactory.checkClassAndSuperName(ProxyFactory.java:748)
    at javassist.util.proxy.ProxyFactory.makeSortedMethodList(ProxyFactory.java:772)
    at javassist.util.proxy.ProxyFactory.computeSignature(ProxyFactory.java:781)
    at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:392)
    at br.com.caelum.vraptor4.proxy.JavassistProxifier.proxify(JavassistProxifier.java:89)
    at br.com.caelum.vraptor4.proxy.JavassistProxifier$Proxy$_$$_WeldClientProxy.proxify(Unknown Source)
    at br.com.caelum.vraptor4.view.DefaultLogicResult.forwardTo(DefaultLogicResult.java:91)

**Comment by filipesg** [comment]
Got the same error here. I'm using Vraptor 4.1.4.

Executing:
`validator.onErrorRedirectTo("/");`

Error:
`java.lang.RuntimeException: java.lang.String is final
	at javassist.util.proxy.ProxyFactory.checkClassAndSuperName(ProxyFactory.java:805)
	at javassist.util.proxy.ProxyFactory.makeSortedMethodList(ProxyFactory.java:827)
	at javassist.util.proxy.ProxyFactory.computeSignature(ProxyFactory.java:837)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:398)
	at javassist.util.proxy.ProxyFactory.create(ProxyFactory.java:676)
	at javassist.util.proxy.ProxyFactory.create(ProxyFactory.java:661)
	at br.com.caelum.vraptor.proxy.JavassistProxifier.createInstance(JavassistProxifier.java:72)
	at br.com.caelum.vraptor.proxy.JavassistProxifier.proxify(JavassistProxifier.java:64)
	at br.com.caelum.vraptor.proxy.JavassistProxifier$Proxy$_$$_WeldClientProxy.proxify(Unknown Source)
	at br.com.caelum.vraptor.util.test.MockResult$1.intercept(MockResult.java:98)
	at br.com.caelum.vraptor.proxy.JavassistProxifier$MethodInvocationAdapter.invoke(JavassistProxifier.java:106)
	at br.com.caelum.vraptor.view.LogicResult_$$_jvst347_0.redirectTo(LogicResult_$$_jvst347_0.java)
	at br.com.caelum.vraptor.validator.AbstractValidator.onErrorRedirectTo(AbstractValidator.java:44)
	at br.com.caelum.vraptor.validator.AbstractValidator.onErrorRedirectTo(AbstractValidator.java:49)
	at br.com.caelum.vraptor.validator.DefaultValidator$Proxy$_$$_WeldClientProxy.onErrorRedirectTo(Unknown Source)
	...
	...
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:75)
	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack.start(DefaultInterceptorStack.java:93)
	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$$_WeldClientProxy.start(Unknown Source)
	at br.com.caelum.vraptor.observer.RequestHandlerObserver.handle(RequestHandlerObserver.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:93)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:266)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:253)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:232)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:169)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:165)
	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:119)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:112)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:83)
	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1368)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`
