### ISSUE TITLE
Getting exception when default messages_en_US is missing

### ISSUE THREAD

**Issue by surajchhetry** [caelum/vraptor4#920]
11:55:52,099 WARN  [br.com.caelum.vraptor.core.JstlLocalization] (default task-29) couldn't find      message bundle, creating an empty one: java.util.MissingResourceException: Can't find bundle for     base name messages, locale en_US
  		at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)    [rt.jar:1.8.0_11]
  		at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387) [rt.jar:1.8.0_11]
    		at java.util.ResourceBundle.getBundle(ResourceBundle.java:845) [rt.jar:1.8.0_11]
   		at br.com.caelum.vraptor.core.JstlLocalization.extractUnsafeBundle(JstlLocalization.java:78)     [vraptor-4.1.4.jar:]
    		at br.com.caelum.vraptor.core.JstlLocalization.getBundle(JstlLocalization.java:69) [vraptor-  4.1.4.jar:]

**Comment by surajchhetry** [comment]
Since it is just *warning* ... this issue can be deleted.

**Comment by garcia-jj** [comment]
Hi @surajchhetry. So I'll close this issue. Keep asking us if you have any question. Best regards.
