### ISSUE TITLE
Do not log exception when there is no environment.properties

### ISSUE THREAD

**Issue by nykolaslima** [caelum/vraptor4#956]
When we don't have a `environment.properties` file, VRaptor latest version is logging:
```
WARN [http-bio-8080-exec-1] (DefaultEnvironment.java:103) - Could not find the file environment.properties to load.
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at br.com.caelum.vraptor.environment.DefaultEnvironment.loadAndPut(DefaultEnvironment.java:100)
	at br.com.caelum.vraptor.environment.DefaultEnvironment.getProperties(DefaultEnvironment.java:82)
	at br.com.caelum.vraptor.environment.DefaultEnvironment.has(DefaultEnvironment.java:168)
	at br.com.caelum.vraptor.environment.DefaultEnvironment.get(DefaultEnvironment.java:173)

```

We should only log the warn message and not the exception. This could led users to think that it's a unexpected behaviour.

What do you think guys? @Turini @lucascs

**Comment by Turini** [comment]
+1 to keep the warn, removing the exception

**Comment by lucascs** [comment]
+1

**Comment by CoderSquirrel** [comment]
@Turini isso ja foi implementado? Esse log fica aparecendo em cada nova requisição. Estou usando o 4.2.0-Final no repositorio mvn

**Comment by Turini** [comment]
@CoderSquirrel foi sim, nesse PR: 
https://github.com/caelum/vraptor4/pull/1101
posso fazer um release de uma nova versão do vraptor pra entrar esse até o final de semana
(;

**Comment by Turini** [comment]
está feito! 
em algumas horas o 4.2.1 já deve estar disponível no repositório do maven
