### ISSUE TITLE
Managing sessions on VRaptor 4

### ISSUE THREAD

**Issue by danilomunoz** [caelum/vraptor4#958]
Recently we updated from vraptor 3 to 4 and we kept using the same method for managing the sessions. The problem is that now we are receiving a WELD error message while destroying the session.

The error occurs on MySessionListener#sessionDestroyed. It looks like sessionManager object are proxied and the while debugging it doesn't enter the invalidateSession method.

web.xml:
```xml
<listener>
	<listener-class>xpto.MySessionListener</listener-class>
</listener>
```

MyListener
```java
package xpto;

import javax.inject.Inject;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionListener;

public class MySessionListener implements HttpSessionListener {
	@Inject
	private MySessionManager sessionManager;
	
	@Override
	public void sessionCreated(HttpSessionEvent session) {
		sessionManager.newSession(session.getSession());
	}

	@Override
	public void sessionDestroyed(HttpSessionEvent session) {
		try {
			HttpSession httpSession = session.getSession();
			sessionManager.invalidateSession(httpSession, null);
		} catch (Exception e) {
			//The error are logged here!!!
		}
	}
}
```

MySessionManager
```java
@SessionScoped
public class MySessionManager implements Serializable {
	//Controls the sessions in a map
}
```

The stacktrace:
```
org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.SessionScoped
        at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:691)
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:79)
        at org.jboss.weld.bean.proxy.CachedBeanInstance.getInstance(CachedBeanInstance.java:66)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
        at xpto.MySessionManager$Proxy$_$$_WeldClientProxy.invalidateSession(Unknown Source)
        at xpto.MySessionListener.sessionDestroyed(MySessionListener.java:27)
        at org.apache.catalina.session.StandardSession.expire(StandardSession.java:846)
        at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:704)
        at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:570)
        at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:555)
        at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5532)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1378)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1382)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1382)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1350)
        at java.lang.Thread.run(Thread.java:745)

```

Please, let me know if the github is the better place to post this kind of question.
Thank you guys!

**Comment by renanigt** [comment]
Try annotate with `@Named`.

**Comment by danilomunoz** [comment]
It still happens .... :-(

I think the problem is related for injecting the request. More details about MySessionManager:
```java
@SessionScoped
public class MySessionManager implements Serializable {
	@Inject
	private HttpServletRequest request;

	//Controls the sessions in a map

}
```

Is there some another way in VRaptor, like Events, that could help me catching the Session Created and Session Destroyed events?

**Comment by renanigt** [comment]
I was wrong, `@Named` is just needed to use in the view...

**Comment by danilomunoz** [comment]
Ok. Thanks for your help.

**Comment by mariofts** [comment]
2 guesses (didn't tried): 

1 - try to declare your listener before weld's listener.
2 - try to declare a method that disposes the session instead of the listener. Something like:

````java
public void sessionClose( @Disposes HttpSession s){
 //your code here...
}
````

**Comment by mariofts** [comment]
Also there's something about this in weld docs: https://docs.jboss.org/weld/reference/latest/en-US/html/environments.html#_servlet_containers_such_as_tomcat_or_jetty

Look at the note in that section.

**Comment by danilomunoz** [comment]
Problem solved!

The big mistakes was that MySessionManager was @SessionScoped. I don't know why, but this was added during the migration from vraptor 3 to vraptor 4. It was singleton in the last version...

Thank you guys for your comments. It helped us a lot to identify this problem.
